server.port=8080

spring.datasource.url=jdbc:mysql://db.localhelp.store:3306/appdb
spring.datasource.username=appuser
spring.datasource.password=app123


spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=never

spring.jpa.show-sql=true
